load("@gazelle//:def.bzl", "gazelle")
load("@rules_rust_mdbook//:defs.bzl", "mdbook", "mdbook_server")

# gazelle:prefix github.com/qhai-dev/kairo

# gazelle:exclude deploy
# gazelle:exclude devenv
# gazelle:exclude docs
# gazelle:exclude frontend
# gazelle:exclude infra
gazelle(
    name = "gazelle",
)

mdbook(
    name = "book",
    srcs = glob(["docs/**/*.md"]),
    book = "//:docs.toml",
)

mdbook_server(
    name = "server",
    book = ":book",
)
